"""Added updated_at to TimestampMixin

Revision ID: 327da2719f0e
Revises: 1e92150b3c99
Create Date: 2016-01-09 19:24:43.956112

"""

# revision identifiers, used by Alembic.
revision = '327da2719f0e'
down_revision = '1e92150b3c99'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types.arrow import ArrowType


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DocStoreDocument', sa.Column('updated_at', ArrowType(), nullable=True))
    op.add_column('SerialNumber', sa.Column('updated_at', ArrowType(), nullable=True))
    op.add_column('SerialNumberAssociation', sa.Column('updated_at', ArrowType(), nullable=True))
    op.add_column('TestResult', sa.Column('updated_at', ArrowType(), nullable=True))
    op.add_column('TestSuiteResult', sa.Column('updated_at', ArrowType(), nullable=True))
    op.add_column('VendorPartMap', sa.Column('updated_at', ArrowType(), nullable=True))
    op.add_column('VendorPartNumber', sa.Column('updated_at', ArrowType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('VendorPartNumber', 'updated_at')
    op.drop_column('VendorPartMap', 'updated_at')
    op.drop_column('TestSuiteResult', 'updated_at')
    op.drop_column('TestResult', 'updated_at')
    op.drop_column('SerialNumberAssociation', 'updated_at')
    op.drop_column('SerialNumber', 'updated_at')
    op.drop_column('DocStoreDocument', 'updated_at')
    ### end Alembic commands ###
